# Generated by Django 5.1.4 on 2024-12-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangay',
            },
        ),
        migrations.CreateModel(
            name='Municpality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipality',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('for_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.municpality')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, help_text='Beneficiary first name', max_length=255)),
                ('middlename', models.CharField(db_index=True, help_text='Beneficiary middle name', max_length=255)),
                ('lastname', models.CharField(db_index=True, help_text='Beneficiary last name', max_length=255)),
                ('extension', models.CharField(blank=True, choices=[('None', 'None'), ('Sr.', 'Sr.'), ('Jr.', 'Jr.')], db_index=True, help_text='Extension', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender', max_length=255)),
                ('purok', models.CharField(help_text='Purok', max_length=255)),
                ('street', models.CharField(help_text='Street', max_length=255)),
                ('province', models.CharField(help_text='Province', max_length=255)),
                ('region', models.CharField(help_text='Region', max_length=255)),
                ('mobile_number', models.CharField(help_text='Mobile Number', max_length=11)),
                ('landline_number', models.CharField(blank=True, help_text='Landline Number', max_length=255, null=True)),
                ('dob', models.CharField(help_text='Date of Birth', max_length=255)),
                ('pob', models.CharField(help_text='Place of Birth', max_length=255)),
                ('provice_place_of_birth', models.CharField(help_text='Provice Place Of Birth', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('Pre-school', 'Pre-school'), ('Elementary', 'Elementary'), ('High School', 'High School'), ('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School'), ('College', 'College'), ('Vocational', 'Vocational'), ('Post-graduate', 'Post-graduate'), ('None', 'None')], help_text='Highest Formal Education', max_length=255)),
                ('is_pwd', models.BooleanField(default=False, help_text='Person with disability')),
                ('is_fourps', models.BooleanField(default=False, help_text="4P's Beneficiary")),
                ('is_member_in_ip', models.BooleanField(default=False, help_text='Member of an Indigenous Group')),
                ('is_household_head', models.BooleanField(default=False, help_text='Household head')),
                ('is_with_government_id', models.BooleanField(default=False, help_text='Government ID')),
                ('is_member_in_any_cooperative', models.BooleanField(default=False, help_text='Member in any cooperative')),
                ('member_in_ip_specific', models.CharField(blank=True, help_text='Specific Indigenous Group', max_length=255, null=True)),
                ('religion', models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], help_text='Region you belong', max_length=255)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], help_text='Civil status', max_length=255)),
                ('name_of_spouse_if_married', models.CharField(blank=True, help_text='Name of spouse if married', max_length=255, null=True)),
                ('mother_maiden_name', models.CharField(help_text='Mother maiden name', max_length=255)),
                ('name_of_household_head', models.CharField(blank=True, help_text='Name of Household', max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], help_text='Relationship', max_length=255, null=True)),
                ('number_of_living_household', models.IntegerField(blank=True, default=0, help_text='No. of living in your household', null=True)),
                ('number_of_male', models.IntegerField(blank=True, default=0, help_text='No. of male in your household', null=True)),
                ('number_of_female', models.IntegerField(blank=True, default=0, help_text='No. of female in your household', null=True)),
                ('type_of_id', models.CharField(blank=True, help_text='What type of ID you have?', max_length=255, null=True)),
                ('id_number', models.CharField(blank=True, help_text='Enter your ID number', max_length=255, null=True)),
                ('specify_cooperative', models.CharField(blank=True, help_text='Specify what cooperative you are member with', max_length=255, null=True)),
                ('person_to_notify', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(help_text='Barangay', on_delete=django.db.models.deletion.CASCADE, to='main.barangay')),
                ('municipality', models.ForeignKey(help_text='Municipality', on_delete=django.db.models.deletion.CASCADE, to='main.municpality')),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Informations',
            },
        ),
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_livelihood', models.CharField(choices=[('Farmer', 'Farmer'), ('Farm Worker', 'Farm Worker'), ('Agri Youth', 'Agri Youth')], max_length=255)),
                ('activity_farmer', models.CharField(blank=True, choices=[('Rice', 'Rice'), ('Corn', 'Corn'), ('Other Crops', 'Other Crops'), ('Livestock', 'Livestock'), ('Poultry', 'Poultry')], max_length=50, null=True)),
                ('specific_farming_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_farmworker', models.CharField(blank=True, choices=[('Land Preparation', 'Land Preparation'), ('Planting', 'Planting'), ('Cultivation', 'Cultivation'), ('Harvesting', 'Harvesting'), ('Others', 'Others')], max_length=50, null=True)),
                ('specific_farmworker_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_agriyouth', models.CharField(blank=True, choices=[('1', 'Part of a farming household'), ('2', 'Attending/attended formal agri-fishery related course'), ('3', 'Attending/attended non-formal agri-fishery related course'), ('4', 'Participated in any agricultural activity/program.'), ('5', 'Others')], max_length=50, null=True)),
                ('specific_agriyouth_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personalinformation')),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
            },
        ),
    ]
