# Generated by Django 5.1.4 on 2024-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='member_in_ip_specific',
            field=models.CharField(help_text='Specific Indigenous Group', max_length=255),
        ),
    ]
