# Generated by Django 5.1.4 on 2024-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='farmer_type',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Farm Worker', 'Farm Worker'), ('Agri Youth', 'Agri Youth')], default='Farmer', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=100, null=True),
        ),
    ]
