# Generated by Django 5.1.4 on 2024-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_personalinformation_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='is_household_head',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='member_in_ip_specific',
            field=models.CharField(blank=True, help_text='Specific Indigenous Group', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name_of_spouse_if_married',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_female',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_living_household',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_male',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], max_length=255, null=True),
        ),
    ]
