# Generated by Django 5.1.4 on 2025-01-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification_farmer_type_alter_farmprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.municpality'),
        ),
    ]
