# Generated by Django 5.1.4 on 2024-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_personalinformation_is_household_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='specify_cooperative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
