# Generated by Django 5.1.4 on 2025-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_barangay_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='farmer_activty',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Corn', 'Corn'), ('Other Crops', 'Other Crops'), ('Livestock', 'Livestock'), ('Poultry', 'Poultry'), ('Land Preparation', 'Land Preparation'), ('Planting', 'Planting'), ('Cultivation', 'Cultivation'), ('Harvesting', 'Harvesting'), ('Others', 'Others')], default='Rice', max_length=255),
        ),
    ]
