# Generated by Django 5.1.4 on 2024-12-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_personalinformation_specify_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personalinformation')),
            ],
        ),
    ]
