# Generated by Django 5.1.4 on 2024-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notificationsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
