# Generated by Django 5.1.4 on 2025-01-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_barangay_date_added_municpality_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason why disapproved', max_length=255, null=True),
        ),
    ]
