# Generated by Django 5.1.4 on 2024-12-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notificationsent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='is_member_in_ip',
            field=models.BooleanField(default=False, help_text='Member of an Indigenous Group'),
        ),
    ]
