# Generated by Django 5.1.4 on 2025-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_farmprofile_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='middlename',
            field=models.CharField(blank=True, db_index=True, help_text='Beneficiary middle name', max_length=255, null=True),
        ),
    ]
