# Generated by Django 5.1.4 on 2024-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_personalinformation_is_household_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], help_text='Civil status', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='id_number',
            field=models.CharField(blank=True, help_text='Enter your ID number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='is_household_head',
            field=models.BooleanField(default=False, help_text='Household head'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='is_member_in_any_cooperative',
            field=models.BooleanField(default=False, help_text='Member in any cooperative'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='is_with_government_id',
            field=models.BooleanField(default=False, help_text='Government ID'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mother_maiden_name',
            field=models.CharField(help_text='Mother maiden name', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name_of_household_head',
            field=models.CharField(help_text='Name of Household', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name_of_spouse_if_married',
            field=models.CharField(blank=True, help_text='Name of spouse if married', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_female',
            field=models.IntegerField(blank=True, default=0, help_text='No. of female in your household', null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_living_household',
            field=models.IntegerField(blank=True, default=0, help_text='No. of living in your household', null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='number_of_male',
            field=models.IntegerField(blank=True, default=0, help_text='No. of male in your household', null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father')], help_text='Relationship', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], help_text='Region you belong', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='specify_cooperative',
            field=models.CharField(blank=True, help_text='Specify what cooperative you are member with', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='type_of_id',
            field=models.CharField(blank=True, help_text='What type of ID you have?', max_length=255, null=True),
        ),
    ]
