# Generated by Django 5.1.4 on 2024-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_personalinformation_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='extension',
            field=models.CharField(blank=True, choices=[('Sr.', 'Sr.'), ('Jr.', 'Jr.')], db_index=True, help_text='Extension', max_length=255, null=True),
        ),
    ]
